from .Inbox_select_all_mark_as_read import Inbox_select_all_mark_as_read
from .Spam_select_all_mark_as_read import Spam_select_all_mark_as_read
from .Spam_report_all_to_inbox import Spam_report_all_to_inbox