# Generated by Django 3.0.5 on 2020-04-18 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('background_task', '0002_auto_20170927_1109'),
        ('universalbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskadaptor',
            name='task',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='background_task.Task'),
        ),
    ]
