# Generated by Django 3.0.5 on 2020-04-20 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universalbot', '0003_taskadaptor_completed_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP Address')),
                ('port', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(65535), django.core.validators.MinValueValidator(0)])),
                ('active', models.BooleanField(default=True, help_text='Active means that the server is up and running and is ready to use.')),
            ],
            options={
                'db_table': 'servers',
            },
        ),
        migrations.AddField(
            model_name='taskadaptor',
            name='servers',
            field=models.ManyToManyField(to='universalbot.Server'),
        ),
    ]
