# Generated by Django 3.0.5 on 2020-05-06 15:06

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('universalbot', '0004_auto_20200420_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskadaptor',
            name='progress',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='actions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, '(Inbox), Select all mark as read.'), (2, '(Spam), Select all mark as read.'), (4, '(Spam), Report all to inbox.'), (5, '(Inbox), Archive all.'), (3, '(Inbox), Open messages.')], max_length=256),
        ),
    ]
