# Generated by Django 3.0.5 on 2020-05-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universalbot', '0006_taskadaptor_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='password',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='proxy',
            name='username',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='proxy',
            field=models.GenericIPAddressField(verbose_name='Proxy IP Address'),
        ),
        migrations.AlterField(
            model_name='taskadaptor',
            name='servers',
            field=models.ManyToManyField(limit_choices_to={'active': True}, to='universalbot.Server', verbose_name='Servers/RDPs'),
        ),
    ]
