# Generated by Django 3.0.5 on 2020-05-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universalbot', '0008_profile_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='default',
            field=models.BooleanField(default=False, help_text="Will be used for profiles that don't have their proxies."),
        ),
    ]
