# Generated by Django 3.0.5 on 2020-05-08 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('universalbot', '0009_proxy_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proxy',
            name='proxy_type',
            field=models.IntegerField(choices=[(1, 'HTTP/HTTPS'), (2, 'Socket4/Socket5')], default=1, verbose_name='Type'),
        ),
    ]
