# Generated by Django 3.0.5 on 2020-05-19 21:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universalbot', '0012_auto_20200508_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='capacity',
            field=models.IntegerField(default=4, help_text='How many profiles this server can handle concurrently, (from 1 to 50).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='port',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(65535), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='server',
            name='port',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(65535), django.core.validators.MinValueValidator(1)]),
        ),
    ]
