# Generated by Django 3.0.5 on 2020-06-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universalbot', '0014_atm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='profiles',
            field=models.ManyToManyField(blank=True, limit_choices_to={'status': True}, to='universalbot.Profile'),
        ),
    ]
