# Generated by Django 3.0.5 on 2020-06-16 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universalbot', '0015_auto_20200614_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskadaptor',
            old_name='current',
            new_name='qsize',
        ),
    ]
