# Generated by Django 3.0.5 on 2020-06-16 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universalbot', '0016_auto_20200616_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskadaptor',
            name='progress',
        ),
    ]
