# Generated by Django 3.0.5 on 2020-06-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universalbot', '0017_remove_taskadaptor_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskadaptor',
            name='total_qsize',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
