# Generated by Django 3.0.5 on 2020-06-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universalbot', '0018_taskadaptor_total_qsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskadaptor',
            name='queue_status',
            field=models.IntegerField(choices=[(0, 'Processing...'), (1, 'Completed'), (2, 'Empty')], default=2),
        ),
    ]
