# Generated by Django 3.0.5 on 2020-06-20 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universalbot', '0019_taskadaptor_queue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskadaptor',
            name='queue_status',
            field=models.IntegerField(choices=[(0, 'Processing'), (1, 'Completed'), (2, 'Empty')], default=2),
        ),
        migrations.CreateModel(
            name='Deleted_queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universalbot.TaskAdaptor')),
            ],
        ),
    ]
