# Generated by Django 3.0.5 on 2020-06-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universalbot', '0020_auto_20200620_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Server name'),
        ),
    ]
